# What is PyTorch?
It's a python based scientific computing package targeted at two sets of audiences:

- A replacement for NumPy to use the power of GPUs
- a deep learning research platform that provides max flexibility and speed

## Tensors

Tensors are similar to NumPy's ndarrays, with the addition that Tensors can also be used on a GPU to accelerate computing.

In [1]:
from __future__ import print_function
import torch

In [36]:
# 5x5 uninitialized matrix
x = torch.empty(5, 5)
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [37]:
# 6x6 randomly initialized matrix
x = torch.rand(6, 6)
print(x)

tensor([[0.8209, 0.0377, 0.6134, 0.7565, 0.2979, 0.3036],
        [0.8277, 0.2629, 0.3097, 0.4658, 0.4472, 0.0484],
        [0.0125, 0.2452, 0.7828, 0.3846, 0.9740, 0.6595],
        [0.9850, 0.7121, 0.8365, 0.5641, 0.9867, 0.8554],
        [0.9915, 0.4676, 0.2354, 0.9021, 0.1514, 0.0314],
        [0.5880, 0.5091, 0.7824, 0.2825, 0.0906, 0.9401]])


In [39]:
# 5x3 matrix filled zeros and of dtype long:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [40]:
# tensor constructed directly from data
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [43]:
# create tensor based on existing tensor

x= x.new_ones(5, 3, dtype=torch.double) # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float) # override dtype!
print(x)

print('Size of tensor')
print(x.size())

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.5411, -0.0655,  1.0977],
        [-1.6727,  0.0216, -0.6620],
        [ 1.1233,  0.9863,  1.9779],
        [-1.5664, -1.1773, -0.0081],
        [ 2.0390,  0.4050, -0.1713]])
Size of tensor
torch.Size([5, 3])


## Operation

There are multiple syntaxes for operation.

### Addition

In [61]:
y = torch.rand(5, 3)

print("x =")
print(x)
print('x.shape:', str(x.shape))
print('-'*45)
print("y =")
print(y)
print('y.shape:', str(y.shape))

x =
tensor([[ 0.5411, -0.0655,  1.0977],
        [-1.6727,  0.0216, -0.6620],
        [ 1.1233,  0.9863,  1.9779],
        [-1.5664, -1.1773, -0.0081],
        [ 2.0390,  0.4050, -0.1713]])
x.shape: torch.Size([5, 3])
---------------------------------------------
y =
tensor([[0.0043, 0.8592, 0.0397],
        [0.1341, 0.7669, 0.2296],
        [0.2005, 0.6489, 0.3297],
        [0.8118, 0.6868, 0.3083],
        [0.1220, 0.5192, 0.4665]])
y.shape: torch.Size([5, 3])


In [64]:
# syntax 1
print('x + y =')
print(x+y)
print('(x+y).shape', str((x+y).shape))

x + y =
tensor([[ 0.5454,  0.7937,  1.1374],
        [-1.5386,  0.7885, -0.4324],
        [ 1.3238,  1.6352,  2.3076],
        [-0.7545, -0.4905,  0.3002],
        [ 2.1609,  0.9242,  0.2952]])
(x+y).shape torch.Size([5, 3])


In [63]:
# syntax 2
print('x + y =')
result = torch.empty(5, 3)
print(torch.add(x,y, out=result))
print('(x+y).shape', str((x+y).shape))

x + y =
tensor([[ 0.5454,  0.7937,  1.1374],
        [-1.5386,  0.7885, -0.4324],
        [ 1.3238,  1.6352,  2.3076],
        [-0.7545, -0.4905,  0.3002],
        [ 2.1609,  0.9242,  0.2952]])
(x+y).shape torch.Size([5, 3])


In [65]:
# syntax 3
print('x + y =')
print(y.add_(x))

x + y =
tensor([[ 0.5454,  0.7937,  1.1374],
        [-1.5386,  0.7885, -0.4324],
        [ 1.3238,  1.6352,  2.3076],
        [-0.7545, -0.4905,  0.3002],
        [ 2.1609,  0.9242,  0.2952]])


### Resizing/ Reshaping a tensor

In [67]:
x = torch.randn(4, 4)
y = x.view(4*4)
z = x.view(-1, 8) # the size -1 is inferred from other dims
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


### Converting a Torch Tensor to a NumPy Array

In [69]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [70]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [71]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


### Converting a NumPy Array to Torch Tensor

In [72]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


### CUDA Tensors
Tensors can be moved onto any device using the .to method

In [74]:
# check for CUDA availability
# we will use "torch.device" objects to move tensors in and out of GPU

if torch.cuda.is_available():
    device = torch.device('cuda')         # a CUDA device object
    y = torch.ones_like(x, device=device) # directly create a tensor on GPU
    x = x.to(device)                      # or just use strings ".to('cuda')"
    z = x+y
    print(z)
    print(z.to('cpu', torch.double))      # ".to" can also change dtype together

tensor([[ 1.6713,  2.6539,  1.2132,  1.4949],
        [-0.0493,  1.3671, -0.5746,  1.9113],
        [ 1.4553, -0.3207,  0.7920, -1.1936],
        [ 0.7932, -0.2094,  1.9910,  0.9120]], device='cuda:0')
tensor([[ 1.6713,  2.6539,  1.2132,  1.4949],
        [-0.0493,  1.3671, -0.5746,  1.9113],
        [ 1.4553, -0.3207,  0.7920, -1.1936],
        [ 0.7932, -0.2094,  1.9910,  0.9120]], dtype=torch.float64)
