## Introduction to Torch's tensor library
All of deep learning is computations on tensors, which are generalizations of a matrix that can be indexed in more than 2 dimensions. We will see exactly what this means in-depth later.

In [1]:
import torch
import torch.autograd as autograd
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

torch.manual_seed(1)

In [2]:
# torch.tensor(data) creates a torch.Tensor object with the given data.
V_data = [1., 2., 3.]
V = torch.tensor(V_data)
print(V)

# creates a matrix
M_data = [[1., 2., 3.], [4., 5., 6]]
M = torch.tensor(M_data)
print(M)

# creates a 3D tensor of size 2x2x2.
T_data = [[[1., 2.], [3., 4.]],
          [[5., 6.], [7., 8.]]]
T = torch.tensor(T_data)
print(T)

tensor([1., 2., 3.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [4]:
# Index into V and get a scalar (0-D tensor)
print(V[0])
# get a python number from it
print(V[0].item())

# Index into M and get a vector
print(M[0])

# Index into T and get a matrix
print(T[0])

tensor(1.)
1.0
tensor([1., 2., 3.])
tensor([[1., 2.],
        [3., 4.]])


In [5]:
x = torch.randn((3, 4, 5))
print(x)

tensor([[[-1.5256, -0.7502, -0.6540, -1.6095, -0.1002],
         [-0.6092, -0.9798, -1.6091, -0.7121,  0.3037],
         [-0.7773, -0.2515, -0.2223,  1.6871,  0.2284],
         [ 0.4676, -0.6970, -1.1608,  0.6995,  0.1991]],

        [[ 0.8657,  0.2444, -0.6629,  0.8073,  1.1017],
         [-0.1759, -2.2456, -1.4465,  0.0612, -0.6177],
         [-0.7981, -0.1316,  1.8793, -0.0721,  0.1578],
         [-0.7735,  0.1991,  0.0457,  0.1530, -0.4757]],

        [[-0.1110,  0.2927, -0.1578, -0.0288,  0.4533],
         [ 1.1422,  0.2486, -1.7754, -0.0255, -1.0233],
         [-0.5962, -1.0055,  0.4285,  1.4761, -1.7869],
         [ 1.6103, -0.7040, -0.1853, -0.9962, -0.8313]]])


In [6]:
# You can operate on tensors in the ways you would expect.
x = torch.tensor([1., 2., 3.])
y = torch.tensor([4., 5., 6.])
z = x + y
print(z)

tensor([5., 7., 9.])


In [11]:
# By default, it concatenates along the first axis (concatenates rows)
x_1 = torch.randn(2, 5)
y_1 = torch.randn(3, 5)
z_1 = torch.cat([x_1, y_1])

# concatenate columns:
x_2 = torch.randn(2, 3)
y_2 = torch.randn(2, 5)
# second arg specifies which axis to concat along
z_2 = torch.cat([x_2, y_2], 1)

# If your tensors are not compatible, torch will complain.
# Uncomment to see the error
# torch.cat([x_1, x_2])

In [14]:
# use .view() method to reshape a tensor
x = torch.randn(2, 3, 4)
print(x)
print(x.view(2, 12)) # reshape to 2 rows, 12 cols
# same as above. If one of the dims is -1, its size can be inferred
print(x.view(2, -1))

tensor([[[-1.2778, -0.8878, -0.7847, -0.5275],
         [ 0.2995, -0.3965, -0.5309,  0.9356],
         [ 0.8533, -1.4188,  0.9830, -0.5387]],

        [[ 0.1378,  0.9247,  0.2938,  3.0301],
         [-1.4259,  0.3364, -0.0607, -2.7828],
         [ 1.3489,  0.2684, -1.1277, -0.5994]]])
tensor([[-1.2778, -0.8878, -0.7847, -0.5275,  0.2995, -0.3965, -0.5309,  0.9356,
          0.8533, -1.4188,  0.9830, -0.5387],
        [ 0.1378,  0.9247,  0.2938,  3.0301, -1.4259,  0.3364, -0.0607, -2.7828,
          1.3489,  0.2684, -1.1277, -0.5994]])
tensor([[-1.2778, -0.8878, -0.7847, -0.5275,  0.2995, -0.3965, -0.5309,  0.9356,
          0.8533, -1.4188,  0.9830, -0.5387],
        [ 0.1378,  0.9247,  0.2938,  3.0301, -1.4259,  0.3364, -0.0607, -2.7828,
          1.3489,  0.2684, -1.1277, -0.5994]])
